### PR TITLE
Updated code for 3.0.0ALPHA9

### PR DESCRIPTION
**Pull request by wyt3dr4g0n**
Corrected type casts and block names and various other bits to make compatible with 3.0.0ALPHA9

### CODE REVIEW

**Comment by Ad5001** [comment]
That's nice! How much testing have you done yet?

**Comment by Ad5001** [comment]
Just tried it and it works! Thanks!

**Comment by wyt3dr4g0n** [comment]
No prob! Good generator, I like it better than the default pocketmine maps. Could use some further tweaking but it's good for the most part.

**Comment by AvgZing** [comment]
Wow!

**Pull request merged**
